# Preprocessing

# Import Library

In [1]:
install.packages("tidyverse")

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

In [2]:
library("tidyverse")
options(repr.plot.width=5, repr.plot.height=5)#Default=7x7
library(readxl)
library(dplyr)
library(ggplot2)
library(patchwork)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   4.0.3     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# Loading Datasets

We import the following three primary datasets:

Omics Data: NPX values (expression intensity)

Sample Metadata: Clinical info (Age, Sex, BMI, etc.)

Peptide Count Data: Metrics for protein detection confidence.tics.

## Omic Data

In [3]:
fileDir <- "./ssd/PE_R478/NPXfiles/converted/"
fileName <- "PE_R478_AN01_NPX_2026-04-01_converted.csv"

#All dataset
original_data <- read_delim(str_c(fileDir, fileName), delim = ",") %>%
    column_to_rownames(var = "OlinkID")


class(original_data)
print(str_c("nrow: ", nrow(original_data)))
head(original_data)
original_data[, 1:10] %>% summary()

Rows: 1037 Columns: 405
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (5): OlinkID, Assay, UniProt, Panel, AssayQC
dbl (398): NPX_PE_R478_001, NPX_PE_R478_002, NPX_PE_R478_003, NPX_PE_R478_00...
lgl   (2): NPX_PE_R478_179, NPX_PE_R478_353

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] "data.frame"

[1] "nrow: 1037"

         NPX_PE_R478_001 NPX_PE_R478_002 NPX_PE_R478_003 NPX_PE_R478_004
OID50001 -0.01171356      0.006932191    -0.06015768      0.07824892
OID50002 -0.03204326     -0.102609266     0.13960276     -0.05653804
OID50003  0.00000000      0.000000000     0.00000000      0.00000000
OID50004 -0.25045807      0.650527606    -0.39107567      0.07046210
OID50005 -0.39112543      1.724015667     0.82744160     -0.09665385
OID50006 -0.25262146      0.550598456     0.56447280     -0.38264907
         NPX_PE_R478_005 NPX_PE_R478_006 NPX_PE_R478_007 NPX_PE_R478_008
OID50001  0.02399070     -0.05241133      0.06254033      0.056933078
OID50002 -0.01692001      0.03116824     -0.01382759      0.112088166
OID50003  0.00000000      0.00000000      0.00000000      0.000000000
OID50004  0.37886754     -0.06428148     -0.27637595      0.017537834
OID50005  0.52275142     -0.24552231     -0.22910107     -0.002791673
OID50006  2.06618786      0.84584590      0.00000000      0.541092075
         NPX_PE_R478_009 NPX_PE_R478_010 ⋯ NPX_PE_R478_395 NPX_PE_R478_396
OID50001 -0.040925896     0.001174600    ⋯ -0.07877364     0.09913166
OID50002 -0.076358691     0.114583120    ⋯ -0.04003070     0.01222553
OID50003  0.000000000     0.000000000    ⋯  0.00000000     0.00000000
OID50004  0.003480558    -0.002491659    ⋯  0.23717032     2.09090606
OID50005  0.099649357    -0.492084416    ⋯  6.67040158     0.93701572
OID50006  1.008770719     0.024623735    ⋯ -0.25647734     0.43291377
         NPX_PE_R478_397 NPX_PE_R478_398 NPX_PE_R478_399 NPX_PE_R478_400
OID50001  0.03435176      0.06688375      0.02028098      0.02570169
OID50002 -0.03706888      0.00565720     -0.03339052      0.05227782
OID50003  0.00000000      0.00000000      0.00000000      0.00000000
OID50004  0.65291258      0.02565652      0.11551500      0.06958829
OID50005 -0.08448202     -0.36909647      0.25264893      0.08557878
OID50006  0.47155583     -0.94094302      0.79948180     -0.84770703
         Assay                 UniProt Panel  AssayQC
OID50001 Amplification control AMP1    Reveal NA
OID50002 Incubation control    INC1    Reveal NA
OID50003 Extension control     EXT1    Reveal NA
OID50004 CCND1                 P24385  Reveal PASS
OID50005 CENPS                 Q8N2Z9  Reveal PASS
OID50006 ERG                   P11308  Reveal PASS

 NPX_PE_R478_001    NPX_PE_R478_002   NPX_PE_R478_003    NPX_PE_R478_004
 Min.   :-2.89490   Min.   :-3.4291   Min.   :-3.09235   Min.   :-4.57751
 1st Qu.:-0.35394   1st Qu.:-0.2387   1st Qu.:-0.18101   1st Qu.:-0.20914
 Median :-0.12513   Median : 0.2394   Median : 0.02641   Median : 0.02643
 Mean   :-0.13067   Mean   : 0.3422   Mean   : 0.09240   Mean   : 0.07862
 3rd Qu.: 0.04816   3rd Qu.: 0.8494   3rd Qu.: 0.31641   3rd Qu.: 0.25830
 Max.   : 4.26552   Max.   : 5.3476   Max.   : 4.62521   Max.   : 3.78259
 NPX_PE_R478_005    NPX_PE_R478_006    NPX_PE_R478_007    NPX_PE_R478_008
 Min.   :-3.21855   Min.   :-2.23835   Min.   :-2.61196   Min.   :-2.358279
 1st Qu.: 0.00102   1st Qu.:-0.02987   1st Qu.:-0.57460   1st Qu.:-0.242184
 Median : 0.60028   Median : 0.19705   Median :-0.30414   Median :-0.001345
 Mean   : 0.69905   Mean   : 0.25527   Mean   :-0.27178   Mean   : 0.031724
 3rd Qu.: 1.27891   3rd Qu.: 0.48553   3rd Qu.:-0.03046   3rd Qu.: 0.238341
 Max.   : 7.41774   Max.   : 3.56588   Max.   : 4.28672   Max.   : 4.468267
 NPX_PE_R478_009    NPX_PE_R478_010
 Min.   :-2.74212   Min.   :-2.66124
 1st Qu.:-0.29588   1st Qu.:-0.45037
 Median :-0.02505   Median :-0.17017
 Mean   : 0.00188   Mean   :-0.14791
 3rd Qu.: 0.22960   3rd Qu.: 0.06905
 Max.   : 4.85505   Max.   : 4.77866

## OIDとUniprotIDのmapping

In [4]:
fileDir <- "./ssd/PE_R478/NPXfiles/original/"
fileName <- "/PE_R478_AN01_NPX_2026-04-01.csv"

temp <- read_delim(str_c(fileDir, fileName), delim = ";") 
head(temp)
temp2 <- temp %>% 
  select(OlinkID, UniProt) %>%
  distinct() %>%
  arrange(OlinkID)

head(temp2)
OID_Uni_map <- temp2

Rows: 466650 Columns: 24
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr (19): SampleID, SampleType, WellID, PlateID, DataAnalysisRefID, OlinkID,...
dbl  (5): Block, Count, ExtNPX, NPX, PCNormalizedNPX

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  SampleID    SampleType WellID PlateID                 DataAnalysisRefID
1 PE_R478_362 SAMPLE     A1     PlateLayout_PE_R478_L01 R10002
2 PE_R478_004 SAMPLE     A2     PlateLayout_PE_R478_L01 R10002
3 PE_R478_194 SAMPLE     A3     PlateLayout_PE_R478_L01 R10002
4 PE_R478_281 SAMPLE     A4     PlateLayout_PE_R478_L01 R10002
5 PE_R478_135 SAMPLE     A5     PlateLayout_PE_R478_L01 R10002
6 PE_R478_177 SAMPLE     A6     PlateLayout_PE_R478_L01 R10002
  OlinkID  UniProt Assay             AssayType Panel  ⋯ Normalization
1 OID50003 EXT1    Extension control ext_ctrl  Reveal ⋯ Intensity
2 OID50003 EXT1    Extension control ext_ctrl  Reveal ⋯ Intensity
3 OID50003 EXT1    Extension control ext_ctrl  Reveal ⋯ Intensity
4 OID50003 EXT1    Extension control ext_ctrl  Reveal ⋯ Intensity
5 OID50003 EXT1    Extension control ext_ctrl  Reveal ⋯ Intensity
6 OID50003 EXT1    Extension control ext_ctrl  Reveal ⋯ Intensity
  PCNormalizedNPX AssayQC SampleQC SoftwareVersion SoftwareName
1 0               NA      PASS     1.3.0           NPX Map
2 0               NA      PASS     1.3.0           NPX Map
3 0               NA      PASS     1.3.0           NPX Map
4 0               NA      PASS     1.3.0           NPX Map
5 0               NA      PASS     1.3.0           NPX Map
6 0               NA      PASS     1.3.0           NPX Map
  PanelDataArchiveVersion PreProcessingVersion PreProcessingSoftware
1 1.8.0                   5.1.0                ngs2counts
2 1.8.0                   5.1.0                ngs2counts
3 1.8.0                   5.1.0                ngs2counts
4 1.8.0                   5.1.0                ngs2counts
5 1.8.0                   5.1.0                ngs2counts
6 1.8.0                   5.1.0                ngs2counts
  InstrumentType
1 Illumina NovaSeq X Plus
2 Illumina NovaSeq X Plus
3 Illumina NovaSeq X Plus
4 Illumina NovaSeq X Plus
5 Illumina NovaSeq X Plus
6 Illumina NovaSeq X Plus

  OlinkID  UniProt
1 OID50001 AMP1
2 OID50002 INC1
3 OID50003 EXT1
4 OID50004 P24385
5 OID50005 Q8N2Z9
6 OID50006 P11308

## Sample Metadata

NPX_PE_R478_179  
NPX_PE_R478_353  
を除外したメタデータを入力した

In [5]:
fileDir <- "./ssd/PE_R478/NPXfiles/"
fileName <- "260701OlinkRevealPancreaticCancer398MetaData.csv"

#Sample info dataset
pro_sample <- read_delim(str_c(fileDir,fileName), delim = ",") 

class(pro_sample)
print(str_c("nrow: ", nrow(pro_sample)))
head(pro_sample)

Rows: 398 Columns: 15
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): Sample ID, icdo3t
dbl (13): 進展度, sex, fvage, CaCo_Status, icdo3m, smoker, py, drinker, quant_d...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] "spec_tbl_df" "tbl_df"      "tbl"         "data.frame"

[1] "nrow: 398"

  Sample ID   進展度 sex fvage CaCo_Status icdo3t icdo3m smoker py drinker
1 PE_R478_001  NA    1   58    0           NA        NA  2       8 1
2 PE_R478_002  NA    1   62    0           NA        NA  2      10 1
3 PE_R478_003  NA    1   68    0           NA        NA  1      24 3
4 PE_R478_004  NA    2   70    0           NA        NA  3       0 3
5 PE_R478_005 440    1   59    1           C252   81403  3       0 3
6 PE_R478_006 430    1   66    1           C250   81403  2      42 1
  quant_drink_gr bmi hx_dm CA19_9   sIL2R
1 25             20  0        4.100  134
2 33             23  0        1.999 5500
3  0             22  0        2.700  259
4  0             26  0        3.800  208
5  0             29  0     1200.000 1181
6 20             22  0      894.400  425

In [6]:
fileDir <- "./ssd/PE_R478/"
fileName <- "PE_R478_SampleID対応表.xlsx"

#Sample info dataset
temp <- read_excel(str_c(fileDir, fileName), skip = 3)

head(temp)
sample_map <- temp

  # Sample ID        RG Sample ID
1 1 olink_hpc4s10134 PE_R478_001
2 2 olink_hpc4s10197 PE_R478_002
3 3 olink_hpc4s10222 PE_R478_003
4 4 olink_hpc4s10313 PE_R478_004
5 5 olink_hpc4s10331 PE_R478_005
6 6 olink_hpc4s10436 PE_R478_006

# Data Preprocessing

## Sample名のNPXの部分を除外

In [7]:
#only number dataset
tempDF <- original_data %>% 
    select(where(~ is.double(.)))

#transpose dataset
tempDF <- t(tempDF)
rownames(tempDF) <- gsub("NPX_", "", rownames(tempDF))
print(str_c("nrow: ", nrow(tempDF)))
head(tempDF)
pro_data <- tempDF

[1] "nrow: 398"

            OID50001     OID50002    OID50003 OID50004    OID50005
PE_R478_001 -0.011713556 -0.03204326 0        -0.25045807 -0.39112543
PE_R478_002  0.006932191 -0.10260927 0         0.65052761  1.72401567
PE_R478_003 -0.060157676  0.13960276 0        -0.39107567  0.82744160
PE_R478_004  0.078248922 -0.05653804 0         0.07046210 -0.09665385
PE_R478_005  0.023990695 -0.01692001 0         0.37886754  0.52275142
PE_R478_006 -0.052411331  0.03116824 0        -0.06428148 -0.24552231
            OID50006   OID50007   OID50008     OID50009   OID50010     ⋯
PE_R478_001 -0.2526215 0.15016670 -0.047767124 -0.3162976 -0.044653639 ⋯
PE_R478_002  0.5505985 2.12804954 -0.040240254  1.3350812  0.269636671 ⋯
PE_R478_003  0.5644728 0.00000000  2.602543033  0.1689984 -0.149231461 ⋯
PE_R478_004 -0.3826491 0.02632158  0.003985377  0.4939300 -0.002797566 ⋯
PE_R478_005  2.0661879 1.18353178  0.329253365  1.2910151  1.488710558 ⋯
PE_R478_006  0.8458459 0.25740414 -0.067080588  0.3520860 -0.108820678 ⋯
            OID51094   OID51095   OID51096     OID51097    OID51098
PE_R478_001  0.7343040  0.1106957  0.058818561 -0.25056479 -0.1450405
PE_R478_002  3.0437799  0.9449602 -0.074905384 -0.02846951 -0.1122920
PE_R478_003 -0.1755618  0.9279319  0.247506062  1.03295073 -0.3208100
PE_R478_004 -0.6034774 -0.4215954  0.008789094 -0.25885057  1.8776520
PE_R478_005  2.4405737  0.7117823  0.082762737  1.66400105  1.6751497
PE_R478_006 -0.1932053 -0.1763277  0.244626878  0.94856834  0.1352742
            OID51099     OID51100   OID51101    OID51102    OID51103
PE_R478_001 -0.262230582 -0.3069646 -0.32811090  0.21699833 -0.10162385
PE_R478_002  0.009770626  0.6058616  1.73276335  0.05060274 -0.07062300
PE_R478_003  0.012948575  0.1874307 -0.01497164 -0.27274720  0.06031307
PE_R478_004  0.111117829  0.4599256  0.32560085  3.78259146 -0.06309908
PE_R478_005  0.773179410  0.7888743  0.49278886  0.19110847  0.22803332
PE_R478_006  0.339222307  0.2458813 -0.38420885  0.28593371  0.01669072

## pro_sampleの列名を英語にする

In [8]:
temp <- pro_sample
colnames(temp)[colnames(temp) == "進展度"] <- "progress"
head(temp)
pro_sample <- temp

  Sample ID   progress sex fvage CaCo_Status icdo3t icdo3m smoker py drinker
1 PE_R478_001  NA      1   58    0           NA        NA  2       8 1
2 PE_R478_002  NA      1   62    0           NA        NA  2      10 1
3 PE_R478_003  NA      1   68    0           NA        NA  1      24 3
4 PE_R478_004  NA      2   70    0           NA        NA  3       0 3
5 PE_R478_005 440      1   59    1           C252   81403  3       0 3
6 PE_R478_006 430      1   66    1           C250   81403  2      42 1
  quant_drink_gr bmi hx_dm CA19_9   sIL2R
1 25             20  0        4.100  134
2 33             23  0        1.999 5500
3  0             22  0        2.700  259
4  0             26  0        3.800  208
5  0             29  0     1200.000 1181
6 20             22  0      894.400  425

## NaN -> 0 (Progress row)

In [9]:
temp <- pro_sample
temp[, "progress"][is.na(temp[, "progress"])] <- 0
head(temp)
pro_sample <- temp

  Sample ID   progress sex fvage CaCo_Status icdo3t icdo3m smoker py drinker
1 PE_R478_001   0      1   58    0           NA        NA  2       8 1
2 PE_R478_002   0      1   62    0           NA        NA  2      10 1
3 PE_R478_003   0      1   68    0           NA        NA  1      24 3
4 PE_R478_004   0      2   70    0           NA        NA  3       0 3
5 PE_R478_005 440      1   59    1           C252   81403  3       0 3
6 PE_R478_006 430      1   66    1           C250   81403  2      42 1
  quant_drink_gr bmi hx_dm CA19_9   sIL2R
1 25             20  0        4.100  134
2 33             23  0        1.999 5500
3  0             22  0        2.700  259
4  0             26  0        3.800  208
5  0             29  0     1200.000 1181
6 20             22  0      894.400  425

# Check missing values

## NAがないか確認

In [10]:
head(pro_data)
any(!is.finite(as.matrix(pro_data)))

            OID50001     OID50002    OID50003 OID50004    OID50005
PE_R478_001 -0.011713556 -0.03204326 0        -0.25045807 -0.39112543
PE_R478_002  0.006932191 -0.10260927 0         0.65052761  1.72401567
PE_R478_003 -0.060157676  0.13960276 0        -0.39107567  0.82744160
PE_R478_004  0.078248922 -0.05653804 0         0.07046210 -0.09665385
PE_R478_005  0.023990695 -0.01692001 0         0.37886754  0.52275142
PE_R478_006 -0.052411331  0.03116824 0        -0.06428148 -0.24552231
            OID50006   OID50007   OID50008     OID50009   OID50010     ⋯
PE_R478_001 -0.2526215 0.15016670 -0.047767124 -0.3162976 -0.044653639 ⋯
PE_R478_002  0.5505985 2.12804954 -0.040240254  1.3350812  0.269636671 ⋯
PE_R478_003  0.5644728 0.00000000  2.602543033  0.1689984 -0.149231461 ⋯
PE_R478_004 -0.3826491 0.02632158  0.003985377  0.4939300 -0.002797566 ⋯
PE_R478_005  2.0661879 1.18353178  0.329253365  1.2910151  1.488710558 ⋯
PE_R478_006  0.8458459 0.25740414 -0.067080588  0.3520860 -0.108820678 ⋯
            OID51094   OID51095   OID51096     OID51097    OID51098
PE_R478_001  0.7343040  0.1106957  0.058818561 -0.25056479 -0.1450405
PE_R478_002  3.0437799  0.9449602 -0.074905384 -0.02846951 -0.1122920
PE_R478_003 -0.1755618  0.9279319  0.247506062  1.03295073 -0.3208100
PE_R478_004 -0.6034774 -0.4215954  0.008789094 -0.25885057  1.8776520
PE_R478_005  2.4405737  0.7117823  0.082762737  1.66400105  1.6751497
PE_R478_006 -0.1932053 -0.1763277  0.244626878  0.94856834  0.1352742
            OID51099     OID51100   OID51101    OID51102    OID51103
PE_R478_001 -0.262230582 -0.3069646 -0.32811090  0.21699833 -0.10162385
PE_R478_002  0.009770626  0.6058616  1.73276335  0.05060274 -0.07062300
PE_R478_003  0.012948575  0.1874307 -0.01497164 -0.27274720  0.06031307
PE_R478_004  0.111117829  0.4599256  0.32560085  3.78259146 -0.06309908
PE_R478_005  0.773179410  0.7888743  0.49278886  0.19110847  0.22803332
PE_R478_006  0.339222307  0.2458813 -0.38420885  0.28593371  0.01669072

[1] FALSE

In [11]:
head(pro_sample)
any(!is.finite(as.matrix(pro_sample)))
target_cols <- c("sex", "fvage", "py", "quant_drink_gr", "bmi", "hx_dm")

colSums(is.na(pro_sample[, target_cols, drop = FALSE]))

  Sample ID   progress sex fvage CaCo_Status icdo3t icdo3m smoker py drinker
1 PE_R478_001   0      1   58    0           NA        NA  2       8 1
2 PE_R478_002   0      1   62    0           NA        NA  2      10 1
3 PE_R478_003   0      1   68    0           NA        NA  1      24 3
4 PE_R478_004   0      2   70    0           NA        NA  3       0 3
5 PE_R478_005 440      1   59    1           C252   81403  3       0 3
6 PE_R478_006 430      1   66    1           C250   81403  2      42 1
  quant_drink_gr bmi hx_dm CA19_9   sIL2R
1 25             20  0        4.100  134
2 33             23  0        1.999 5500
3  0             22  0        2.700  259
4  0             26  0        3.800  208
5  0             29  0     1200.000 1181
6 20             22  0      894.400  425

[1] TRUE

           sex          fvage             py quant_drink_gr            bmi
             0              0              0              0              0
         hx_dm
             0

# 型チェック

In [12]:
non_numeric_cols <- !sapply(temp, is.numeric)
sapply(temp[non_numeric_cols], class)

  Sample ID      icdo3t
"character" "character"

## Check sample data

In [13]:
colSums(is.na(pro_sample))

     Sample ID       progress            sex          fvage    CaCo_Status
             0              0              0              0              0
        icdo3t         icdo3m         smoker             py        drinker
           198            198              0              0              0
quant_drink_gr            bmi          hx_dm         CA19_9          sIL2R
             0              0              0              0              0

がん患者と健常者で、進展度, icdo3t, icdo3mが正しく NA または値が入っているかを検証

In [14]:
error_rows <- pro_sample %>%
  filter(
    (CaCo_Status == 1 & (is.na(progress) | is.na(icdo3t) | is.na(icdo3m))) |
    (CaCo_Status == 0 & (!is.na(progress) | !is.na(icdo3t) | !is.na(icdo3m)))
)

if (nrow(error_rows) == 0) {
  print("No Error")
} else {
  print(paste("Error row: ", nrow(error_rows)))
  error_rows %>% select(CaCo_Status, progress, icdo3t, icdo3m) %>% head()
}

[1] "Error row:  198"

  CaCo_Status progress icdo3t icdo3m
1 0           0        NA     NA
2 0           0        NA     NA
3 0           0        NA     NA
4 0           0        NA     NA
5 0           0        NA     NA
6 0           0        NA     NA

## 除外されたサンプルが他のデータセットでも除外されているか確認

In [15]:
check_missing_ids <- function(df, id_column) {
  
  # 指定された列からIDベクトルを取得し、末尾の数字を抽出
  ids <- df[[id_column]]
  present_numbers <- ids %>% 
    str_extract("\\d+$") %>%   
    as.numeric() %>% 
    unique() %>% 
    sort()
  
  # 1〜400の差分をチェック
  all_numbers <- 1:400
  missing_numbers <- setdiff(all_numbers, present_numbers)
  
  # 結果をリスト形式で返却
  return(list(
    is_complete = (length(missing_numbers) == 0),
    missing_count = length(missing_numbers),
    missing_numbers = missing_numbers
  ))
}

temp <- pro_data %>% 
  as.data.frame() %>%
  rownames_to_column(var = "SampleID")
result1 <- check_missing_ids(temp, "SampleID")
print(result1$missing_numbers)

result2 <- check_missing_ids(pro_sample, "Sample ID")
print(result2$missing_numbers)

result3 <- check_missing_ids(sample_map, "RG Sample ID")
print(result3$missing_numbers)

[1] 179 353
[1] 179 353
integer(0)

## 除外されていないものを除外

In [16]:
temp <- c("PE_R478_179", "PE_R478_353")

temp2 <- sample_map %>% 
  filter(!(`RG Sample ID` %in% temp))

result1 <- check_missing_ids(temp2, "RG Sample ID")
print(result1$missing_numbers)

sample_map <- temp2

[1] 179 353

## Check omics data

### 分散が0のものをみる

In [17]:
temp <- pro_data
zero_var_cols <- apply(temp, 2, function(x) is.numeric(x) && var(x, na.rm = TRUE) == 0)
colnames(temp)[zero_var_cols & !is.na(zero_var_cols)]

[1] "OID50003"

In [18]:
summary(temp[, "OID50003"])
var(temp[, "OID50003"], na.rm = TRUE)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
      0       0       0       0       0       0

[1] 0

In [19]:
temp <- pro_data
temp <- temp[, colnames(temp) != "OID50003", drop = FALSE]
head(temp)

pro_data <- temp

            OID50001     OID50002    OID50004    OID50005    OID50006
PE_R478_001 -0.011713556 -0.03204326 -0.25045807 -0.39112543 -0.2526215
PE_R478_002  0.006932191 -0.10260927  0.65052761  1.72401567  0.5505985
PE_R478_003 -0.060157676  0.13960276 -0.39107567  0.82744160  0.5644728
PE_R478_004  0.078248922 -0.05653804  0.07046210 -0.09665385 -0.3826491
PE_R478_005  0.023990695 -0.01692001  0.37886754  0.52275142  2.0661879
PE_R478_006 -0.052411331  0.03116824 -0.06428148 -0.24552231  0.8458459
            OID50007   OID50008     OID50009   OID50010     OID50011    ⋯
PE_R478_001 0.15016670 -0.047767124 -0.3162976 -0.044653639  0.51639983 ⋯
PE_R478_002 2.12804954 -0.040240254  1.3350812  0.269636671 -0.18246833 ⋯
PE_R478_003 0.00000000  2.602543033  0.1689984 -0.149231461  0.02723937 ⋯
PE_R478_004 0.02632158  0.003985377  0.4939300 -0.002797566 -0.11433296 ⋯
PE_R478_005 1.18353178  0.329253365  1.2910151  1.488710558  1.12320010 ⋯
PE_R478_006 0.25740414 -0.067080588  0.3520860 -0.108820678 -0.25568781 ⋯
            OID51094   OID51095   OID51096     OID51097    OID51098
PE_R478_001  0.7343040  0.1106957  0.058818561 -0.25056479 -0.1450405
PE_R478_002  3.0437799  0.9449602 -0.074905384 -0.02846951 -0.1122920
PE_R478_003 -0.1755618  0.9279319  0.247506062  1.03295073 -0.3208100
PE_R478_004 -0.6034774 -0.4215954  0.008789094 -0.25885057  1.8776520
PE_R478_005  2.4405737  0.7117823  0.082762737  1.66400105  1.6751497
PE_R478_006 -0.1932053 -0.1763277  0.244626878  0.94856834  0.1352742
            OID51099     OID51100   OID51101    OID51102    OID51103
PE_R478_001 -0.262230582 -0.3069646 -0.32811090  0.21699833 -0.10162385
PE_R478_002  0.009770626  0.6058616  1.73276335  0.05060274 -0.07062300
PE_R478_003  0.012948575  0.1874307 -0.01497164 -0.27274720  0.06031307
PE_R478_004  0.111117829  0.4599256  0.32560085  3.78259146 -0.06309908
PE_R478_005  0.773179410  0.7888743  0.49278886  0.19110847  0.22803332
PE_R478_006  0.339222307  0.2458813 -0.38420885  0.28593371  0.01669072

## Export Sample information data file

In [20]:
if (!dir.exists("./Data")) {
  dir.create("./Data")
}

write.csv(pro_data, file = "Data/pro_data.csv", row.names = TRUE)
write.csv(OID_Uni_map, file = "Data/map_OID_Uni.csv", row.names = TRUE)
write.csv(pro_sample, file = "Data/pro_sample.csv", row.names = FALSE)

In [21]:
if (!dir.exists("./ExportData")) {
  dir.create("./ExportData")
}

# データの概要を見る

In [22]:
temp <- pro_sample
head(temp)
cat_cols <- c("sex", "fvage", "py", "quant_drink_gr", "bmi", "hx_dm", "CaCo_Status", "progress")

temp_summary <- temp[, cat_cols, drop = FALSE]

factor_cols <- c("sex", "hx_dm", "CaCo_Status", "progress")
temp_summary[factor_cols] <- lapply(temp_summary[factor_cols], as.factor)

int_cols <- c("fvage", "py", "quant_drink_gr", "bmi")
temp_summary[int_cols] <- lapply(temp_summary[int_cols], as.integer)

summary(temp_summary)

  Sample ID   progress sex fvage CaCo_Status icdo3t icdo3m smoker py drinker
1 PE_R478_001   0      1   58    0           NA        NA  2       8 1
2 PE_R478_002   0      1   62    0           NA        NA  2      10 1
3 PE_R478_003   0      1   68    0           NA        NA  1      24 3
4 PE_R478_004   0      2   70    0           NA        NA  3       0 3
5 PE_R478_005 440      1   59    1           C252   81403  3       0 3
6 PE_R478_006 430      1   66    1           C250   81403  2      42 1
  quant_drink_gr bmi hx_dm CA19_9   sIL2R
1 25             20  0        4.100  134
2 33             23  0        1.999 5500
3  0             22  0        2.700  259
4  0             26  0        3.800  208
5  0             29  0     1200.000 1181
6 20             22  0      894.400  425

 sex         fvage             py         quant_drink_gr        bmi
 1:227   Min.   :16.00   Min.   :  0.00   Min.   :  0.00   Min.   :15.00
 2:171   1st Qu.:56.00   1st Qu.:  0.00   1st Qu.:  0.00   1st Qu.:20.00
         Median :63.00   Median :  0.00   Median :  2.00   Median :22.00
         Mean   :61.56   Mean   : 14.17   Mean   : 13.61   Mean   :22.56
         3rd Qu.:70.00   3rd Qu.: 24.00   3rd Qu.: 19.00   3rd Qu.:25.00
         Max.   :88.00   Max.   :168.00   Max.   :215.00   Max.   :34.00
 hx_dm   CaCo_Status progress
 0:331   0:198       0  :198
 1: 67   1:200       400: 10
                     410: 93
                     420: 15
                     430: 47
                     440: 35

# UniprotIDとProtein Symbolsの表を作成

In [23]:
head(OID_Uni_map)

  OlinkID  UniProt
1 OID50001 AMP1
2 OID50002 INC1
3 OID50003 EXT1
4 OID50004 P24385
5 OID50005 Q8N2Z9
6 OID50006 P11308

Entry nameとAccessionが混在している？

## Entry nameとaccessionを分類

In [24]:
uniprot_list <- as.character(OID_Uni_map$UniProt)

# Accessino pattern
ac_regex <- "^([OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2})$"
is_accession <- grepl(ac_regex, uniprot_list, ignore.case = TRUE)

accessions <- uniprot_list[is_accession]
others     <- uniprot_list[!is_accession]

cat("Accession name: ", head(accessions), ", num: ", length(accessions),"\n")
cat("Others: ", others, ", num: ", length(others),"\n")

Accession name:  P24385 Q8N2Z9 P11308 Q9UI08 Q9UH90 P57764 , num:  1028
Others:  AMP1 INC1 EXT1 A8MVU1_P14598 Q14213_Q8NEV9 P29459_P29460 P43627_P43628 Q29980_Q29983 Q5VY80_Q9BZM5 , num:  9

In [25]:
entry <- others[others %in% c("AMP1", "INC1", "EXT1")]
head(entry)

[1] "AMP1" "INC1" "EXT1"

In [26]:
writeLines(accessions, "./ExportData/uniprot_accessions.txt")
writeLines(as.character(OID_Uni_map$UniProt), "./ExportData/uniprot_ids.txt")

accessionをhttps://www.uniprot.org/id-mapping でGene nameに変換  
出力結果をDataに保存

In [27]:
#PancreasProject/Aichi_Proteomics/Data/idmapping_2026_07_17.tsv.gz
temp <- read_tsv("./Data/idmapping_2026_07_17.tsv.gz")
head(temp)
# Left join and handle missing values
temp2 <- OID_Uni_map %>%
  left_join(temp, by = c("UniProt" = "From")) %>%
  mutate(Symbol = if_else(is.na(To), paste0(UniProt, "*"), To)) %>%
  select(-To)

# Preview result
head(temp2)
val_map <- temp2
write.csv(val_map, file = "Data/map_OID_Uni_Sym.csv", row.names = TRUE)

Rows: 1031 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): From, To

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  From   To
1 P24385 CCND1
2 Q8N2Z9 CENPS
3 P11308 ERG
4 Q9UI08 EVL
5 Q9UH90 FBXO40
6 P57764 GSDMD

  OlinkID  UniProt Symbol
1 OID50001 AMP1    AMP1*
2 OID50002 INC1    INC1*
3 OID50003 EXT1    EXT1*
4 OID50004 P24385  CCND1
5 OID50005 Q8N2Z9  CENPS
6 OID50006 P11308  ERG

# Discoveryとのオミクスの重複を見る

In [28]:
disco <- read_csv("../Proteomics/Data/pro_analyte.csv")
colnames(disco)[1] <- "OID"
head(disco)

disco_uniprot <- unique(na.omit(disco$UniProtID))
val_uniprot   <- unique(na.omit(val_map$UniProt))
overlapping_ids <- intersect(disco_uniprot, val_uniprot)

# Calculate overlap counts
overlap_count  <- length(overlapping_ids)
val_only_count <- length(setdiff(val_uniprot, disco_uniprot))

# Extract IDs only in val_map
val_only_ids <- setdiff(val_uniprot, disco_uniprot)
# Filter val_map using the unmatched IDs vector
val_only_symbols <- val_map %>%
  filter(UniProt %in% val_only_ids) %>%
  select(UniProt, Symbol) %>%
  distinct()


cat("Number of overlapping IDs:", overlap_count, "\n")
cat("Number of IDs in val_map but not in disco:", val_only_count, " (",val_only_ids,")\n")


# Preview the specific IDs missing in disco
head(val_only_symbols)

New names:
• `` -> `...1`
Rows: 5416 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): ...1, Assay, UniProtID, Panel

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  OID      Assay  UniProtID Panel
1 OID40001 ABCF3  Q9NUQ8    Explore_HT
2 OID40002 ABHD5  Q8WTS1    Explore_HT
3 OID40003 ABHD8  Q96I13    Explore_HT
4 OID40004 ACAD9  Q9H845    Explore_HT
5 OID40005 ACSM5  Q6NUN0    Explore_HT
6 OID40006 ADGRF2 Q8IZF7    Explore_HT

Number of overlapping IDs: 1033
Number of IDs in val_map but not in disco: 4  ( AMP1 INC1 EXT1 P48061 )

  UniProt Symbol
1 AMP1    AMP1*
2 INC1    INC1*
3 EXT1    EXT1*
4 P48061  CXCL12

## 重複しているもののみを保存する

## Validation dataの方

In [29]:
# Map overlapping UniProt IDs to OIDs
target_oids <- val_map %>%
  filter(UniProt %in% overlapping_ids) %>%
  pull(OlinkID) %>%
  unique() %>%
  na.omit()

pro_data_filtered <- pro_data[, colnames(pro_data) %in% target_oids]

oid_to_uniprot <- setNames(val_map$UniProt, val_map$OlinkID)
colnames(pro_data_filtered) <- oid_to_uniprot[colnames(pro_data_filtered)]

cat("Number of target OIDs found:", length(target_oids), "\n")
cat("Number of rows extracted from pro_data:", ncol(pro_data_filtered), "\n")
head(pro_data_filtered)

Number of target OIDs found: 1033
Number of rows extracted from pro_data: 1033

            P24385      Q8N2Z9      P11308     Q9UI08     Q9UH90
PE_R478_001 -0.25045807 -0.39112543 -0.2526215 0.15016670 -0.047767124
PE_R478_002  0.65052761  1.72401567  0.5505985 2.12804954 -0.040240254
PE_R478_003 -0.39107567  0.82744160  0.5644728 0.00000000  2.602543033
PE_R478_004  0.07046210 -0.09665385 -0.3826491 0.02632158  0.003985377
PE_R478_005  0.37886754  0.52275142  2.0661879 1.18353178  0.329253365
PE_R478_006 -0.06428148 -0.24552231  0.8458459 0.25740414 -0.067080588
            P57764     Q9UQL6       P01574      K9M1U5      Q14626      ⋯
PE_R478_001 -0.3162976 -0.044653639  0.51639983  1.15091121 -0.02780112 ⋯
PE_R478_002  1.3350812  0.269636671 -0.18246833 -0.07122713 -0.25116759 ⋯
PE_R478_003  0.1689984 -0.149231461  0.02723937  1.25469254  1.00663234 ⋯
PE_R478_004  0.4939300 -0.002797566 -0.11433296 -0.11839815  1.04308756 ⋯
PE_R478_005  1.2910151  1.488710558  1.12320010  0.77514456 -0.16365943 ⋯
PE_R478_006  0.3520860 -0.108820678 -0.25568781  0.88567514  0.05553067 ⋯
            P33316     Q92597     Q9NRA1       Q15643      P35520
PE_R478_001  0.7343040  0.1106957  0.058818561 -0.25056479 -0.1450405
PE_R478_002  3.0437799  0.9449602 -0.074905384 -0.02846951 -0.1122920
PE_R478_003 -0.1755618  0.9279319  0.247506062  1.03295073 -0.3208100
PE_R478_004 -0.6034774 -0.4215954  0.008789094 -0.25885057  1.8776520
PE_R478_005  2.4405737  0.7117823  0.082762737  1.66400105  1.6751497
PE_R478_006 -0.1932053 -0.1763277  0.244626878  0.94856834  0.1352742
            Q15262       P25685     Q9Y570      Q6UB99      P49789
PE_R478_001 -0.262230582 -0.3069646 -0.32811090  0.21699833 -0.10162385
PE_R478_002  0.009770626  0.6058616  1.73276335  0.05060274 -0.07062300
PE_R478_003  0.012948575  0.1874307 -0.01497164 -0.27274720  0.06031307
PE_R478_004  0.111117829  0.4599256  0.32560085  3.78259146 -0.06309908
PE_R478_005  0.773179410  0.7888743  0.49278886  0.19110847  0.22803332
PE_R478_006  0.339222307  0.2458813 -0.38420885  0.28593371  0.01669072

In [30]:
write.csv(pro_data_filtered, file = "./Data/pro_data_common_val.csv", row.names = TRUE)

## Discovery dataの方

In [31]:
head(disco)

  OID      Assay  UniProtID Panel
1 OID40001 ABCF3  Q9NUQ8    Explore_HT
2 OID40002 ABHD5  Q8WTS1    Explore_HT
3 OID40003 ABHD8  Q96I13    Explore_HT
4 OID40004 ACAD9  Q9H845    Explore_HT
5 OID40005 ACSM5  Q6NUN0    Explore_HT
6 OID40006 ADGRF2 Q8IZF7    Explore_HT

In [32]:
pro_data_dis <- read.csv("../Proteomics/Data/pro_data.csv",row.names = 1)
# colnames(pro_data_dis)[1] <- "OID"
head(pro_data_dis)

# Map overlapping UniProt IDs to OIDs
target_oids <- disco %>%
  filter(UniProtID %in% overlapping_ids) %>%
  pull(OID) %>%
  unique() %>%
  na.omit()

pro_data_filtered_dis <- pro_data_dis[, colnames(pro_data_dis) %in% target_oids]

oid_to_uniprot <- setNames(disco$UniProtID, disco$OID)
colnames(pro_data_filtered_dis) <- oid_to_uniprot[colnames(pro_data_filtered_dis)]

cat("Number of target OIDs found:", length(target_oids), "\n")
cat("Number of rows extracted from pro_data:", ncol(pro_data_filtered_dis), "\n")
head(pro_data_filtered_dis)

            OID40001    OID40002   OID40003   OID40004   OID40005   OID40006
PE_R345_001  0.15685708 -1.2809895 -0.6724805 -0.3429793 -0.6828890  0.1856777
PE_R345_002  0.18574294 -0.4411882 -0.1221859  0.2073153  0.2299758 -0.7311536
PE_R345_003 -0.42471153  3.5985347 -0.7250070 -0.3955058  0.1353015 -6.4214376
PE_R345_004 -0.01176647  0.2233665 -1.7551782 -0.2438119  2.1937836  1.1976067
PE_R345_005  0.51619972  0.6541025 -0.2256751  4.5632578 -1.4111702 -0.1941852
PE_R345_006  0.50536247  0.3720525  0.3421305 -0.1465032 -0.4174449  0.5792184
            OID40007   OID40008    OID40009   OID40010    ⋯ OID45493
PE_R345_001 -0.6810284 -1.67851051  0.3181834  0.08219064 ⋯  0.59642473
PE_R345_002  0.2372417 -1.38455559  0.3980275 -1.15338989 ⋯  0.01462026
PE_R345_003 -0.5593040 -2.69787012 -1.3834359 -0.31041128 ⋯ -0.33666581
PE_R345_004  0.9434879 -0.06222494 -0.2885631  0.36374713 ⋯  0.20319734
PE_R345_005  0.7262487  0.01445556 -0.1897302 -0.04877088 ⋯ -0.05412543
PE_R345_006 -1.1078000 -0.85621004 -0.2688374 -1.83662477 ⋯ -0.05701649
            OID45494   OID45495     OID45496    OID45497     OID45498
PE_R345_001  0.4558277  0.261721093  0.19461540  0.419760630  0.67708787
PE_R345_002 -0.6174974  0.222624074  0.08280174  0.116783035  0.31329378
PE_R345_003 -0.5061843 -0.005590452  0.20595378  0.002229884  0.02572184
PE_R345_004  0.4893719  0.412470459  1.02898869  0.626601909  0.39928687
PE_R345_005 -0.1199575 -0.036432928 -0.27784034 -0.269475996  0.11340867
PE_R345_006 -0.4260233 -0.361989997 -0.50155634 -0.229735034 -0.41742363
            OID45499    OID45500    OID45501   OID45502
PE_R345_001  0.10684666  0.37067970  0.4235804  0.54056364
PE_R345_002  0.11748404 -0.17957369  0.6355467  0.10883779
PE_R345_003 -0.08852068 -0.00988637  0.2605036 -0.06812777
PE_R345_004  0.45495652  0.69822771  0.2530163  0.15614326
PE_R345_005 -0.39239378 -0.14166148 -0.4388484  0.09954329
PE_R345_006  0.01744330 -0.16316644 -0.4903883 -0.89916452

Number of target OIDs found: 1033
Number of rows extracted from pro_data: 1033

            P24385     Q8N2Z9      P11308      Q9UI08     Q9UH90
PE_R345_001 -0.6921791  0.01448693  0.02094861  0.7564186 -6.9053523
PE_R345_002 -0.3691756  0.68436321  0.10795933  0.2265691 -0.8956260
PE_R345_003 -2.3946878 -0.34446656  0.32456594 -0.6627454 -0.6180287
PE_R345_004  0.6397468 -0.61830848 -6.10570083 -0.6044629 -0.6606177
PE_R345_005 -0.8205881  1.82880153  0.74355579  0.9447682  0.3743432
PE_R345_006 -0.5041960 -0.12636855 -0.90405553 -1.0680426 -0.4779176
            P57764       Q9UQL6     P01574     K9M1U5     Q14626     ⋯
PE_R345_001 -1.666650995  0.1100459  0.2324701  0.9764344  0.3333238 ⋯
PE_R345_002  0.109438676 -0.3035902  0.9202683  0.5536961  0.2627944 ⋯
PE_R345_003  0.400878277  0.7816446 -1.0830907  1.0179891 -0.4764679 ⋯
PE_R345_004  0.948255944  0.6587508 -5.3075910  1.7526003  0.2424571 ⋯
PE_R345_005 -0.004282433  0.7687704 -0.4727275  2.3798176  0.3552676 ⋯
PE_R345_006 -0.534853990 -1.4516977 -0.6253199 -1.2937845  0.2486178 ⋯
            P23467     P23471      Q9HCK4      P31949     Q9Y286
PE_R345_001  0.1494224  0.10995232  0.04322361 -0.1131859 -0.17305146
PE_R345_002  0.1384166  0.01003162 -0.37550043 -0.2835852 -0.07876471
PE_R345_003  0.2978762  0.21514759 -0.29801920  0.2307418 -0.44669349
PE_R345_004  0.2489813 -0.83676280 -0.02566769  0.7078517  0.09429799
PE_R345_005 -0.7193875 -0.38676094 -0.05782770 -0.2936112 -0.61504308
PE_R345_006  0.2036782  0.66921008 -0.11985187 -0.7077232  0.33114667
            P17405     P16035      O00300     O14836     O75888
PE_R345_001 -0.1885828 -0.50089054 -0.4491717  0.2567558 -0.04720385
PE_R345_002 -0.4623585 -0.05053144 -0.2658149 -0.3297766 -0.09315255
PE_R345_003 -0.2389888 -0.14990336 -0.3684046 -0.7778954  0.26355358
PE_R345_004  0.1436411 -1.10712474 -0.3709440  0.0383825 -0.08879711
PE_R345_005  0.1091076 -0.30424975 -0.0750934 -0.2696089 -0.34519795
PE_R345_006  1.3916908 -0.07769807  0.4186807  0.4991744 -0.40251907

In [33]:
write.csv(pro_data_filtered_dis, file = "./Data/pro_data_common_dis.csv", row.names = TRUE)

In [34]:
write.csv(overlapping_ids, file = "./Data/overlapping_ids.csv", row.names = TRUE)