# Mapping OlinkID and Assay

In [1]:
#Initial setup
import warnings
warnings.filterwarnings('ignore')
from IPython.display import display

import pandas as pd
import os
import numpy as np

In [2]:
fileDir = "./Data/"
fileName = "pro_data.csv"

path = os.path.join(fileDir, fileName)
temp = pd.read_csv(path)
temp.set_index(temp.columns[0],inplace=True)
temp.index.name = None
pro_data = temp
display(pro_data)

fileDir = "./Data/"
fileName = "map_OID_Uni.csv"

path = os.path.join(fileDir, fileName)
IDdata = pd.read_csv(path)
IDdata.set_index(IDdata.columns[0],inplace=True)
IDdata.index.name = None
display(IDdata)

,OID50001,OID50002,OID50004,OID50005,OID50006,OID50007,OID50008,OID50009,OID50010,OID50011,...,OID51094,OID51095,OID51096,OID51097,OID51098,OID51099,OID51100,OID51101,OID51102,OID51103
PE_R478_001,-0.011714,-0.032043,-0.250458,-0.391125,-0.252621,0.150167,-0.047767,-0.316298,-0.044654,0.516400,...,0.734304,0.110696,0.058819,-0.250565,-0.145040,-0.262231,-0.306965,-0.328111,0.216998,-0.101624
PE_R478_002,0.006932,-0.102609,0.650528,1.724016,0.550598,2.128050,-0.040240,1.335081,0.269637,-0.182468,...,3.043780,0.944960,-0.074905,-0.028470,-0.112292,0.009771,0.605862,1.732763,0.050603,-0.070623
PE_R478_003,-0.060158,0.139603,-0.391076,0.827442,0.564473,0.000000,2.602543,0.168998,-0.149231,0.027239,...,-0.175562,0.927932,0.247506,1.032951,-0.320810,0.012949,0.187431,-0.014972,-0.272747,0.060313
PE_R478_004,0.078249,-0.056538,0.070462,-0.096654,-0.382649,0.026322,0.003985,0.493930,-0.002798,-0.114333,...,-0.603477,-0.421595,0.008789,-0.258851,1.877652,0.111118,0.459926,0.325601,3.782591,-0.063099
PE_R478_005,0.023991,-0.016920,0.378868,0.522751,2.066188,1.183532,0.329253,1.291015,1.488711,1.123200,...,2.440574,0.711782,0.082763,1.664001,1.675150,0.773179,0.788874,0.492789,0.191108,0.228033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PE_R478_396,0.099132,0.012226,2.090906,0.937016,0.432914,0.422205,-0.034455,0.301893,-0.417816,0.567447,...,-0.318979,0.567542,-0.176940,-1.468123,0.858104,0.097731,-0.573343,-0.164230,0.004873,-0.195060
PE_R478_397,0.034352,-0.037069,0.652913,-0.084482,0.471556,0.067670,0.048786,1.311366,0.047220,-0.000537,...,0.953380,2.234465,0.233921,-0.020321,3.746860,0.025703,0.553025,0.145132,0.019710,2.857327
PE_R478_398,0.066884,0.005657,0.025657,-0.369096,-0.940943,-0.833491,-0.035938,-0.282643,0.902980,-0.354449,...,0.373973,-0.330692,0.003094,0.760417,-0.094866,-0.042590,0.295296,0.252283,-0.597332,0.102647
PE_R478_399,0.020281,-0.033391,0.115515,0.252649,0.799482,-0.555303,-0.095176,0.147232,-0.232622,0.275772,...,-0.294149,2.978748,-0.111313,-0.910355,0.684876,-0.089939,-0.454858,-0.286652,-0.528971,-0.131158
PE_R478_400,0.025702,0.052278,0.069588,0.085579,-0.847707,-0.578246,-0.034066,-0.313569,-0.271985,0.445230,...,0.034440,-0.259372,-0.228458,-0.224602,-0.230825,-0.132997,-0.373230,-0.033207,-0.627025,0.148722

       OlinkID UniProt
1     OID50001    AMP1
2     OID50002    INC1
3     OID50003    EXT1
4     OID50004  P24385
5     OID50005  Q8N2Z9
...        ...     ...
1033  OID51099  Q15262
1034  OID51100  P25685
1035  OID51101  Q9Y570
1036  OID51102  Q6UB99
1037  OID51103  P49789

[1037 rows x 2 columns]

In [3]:
temp = dict(
    zip(IDdata["OlinkID"], IDdata["UniProt"])
)
temp2 = pro_data.rename(
    columns=temp
)
display(temp2)
pro_data = temp2

,AMP1,INC1,P24385,Q8N2Z9,P11308,Q9UI08,Q9UH90,P57764,Q9UQL6,P01574,...,P33316,Q92597,Q9NRA1,Q15643,P35520,Q15262,P25685,Q9Y570,Q6UB99,P49789
PE_R478_001,-0.011714,-0.032043,-0.250458,-0.391125,-0.252621,0.150167,-0.047767,-0.316298,-0.044654,0.516400,...,0.734304,0.110696,0.058819,-0.250565,-0.145040,-0.262231,-0.306965,-0.328111,0.216998,-0.101624
PE_R478_002,0.006932,-0.102609,0.650528,1.724016,0.550598,2.128050,-0.040240,1.335081,0.269637,-0.182468,...,3.043780,0.944960,-0.074905,-0.028470,-0.112292,0.009771,0.605862,1.732763,0.050603,-0.070623
PE_R478_003,-0.060158,0.139603,-0.391076,0.827442,0.564473,0.000000,2.602543,0.168998,-0.149231,0.027239,...,-0.175562,0.927932,0.247506,1.032951,-0.320810,0.012949,0.187431,-0.014972,-0.272747,0.060313
PE_R478_004,0.078249,-0.056538,0.070462,-0.096654,-0.382649,0.026322,0.003985,0.493930,-0.002798,-0.114333,...,-0.603477,-0.421595,0.008789,-0.258851,1.877652,0.111118,0.459926,0.325601,3.782591,-0.063099
PE_R478_005,0.023991,-0.016920,0.378868,0.522751,2.066188,1.183532,0.329253,1.291015,1.488711,1.123200,...,2.440574,0.711782,0.082763,1.664001,1.675150,0.773179,0.788874,0.492789,0.191108,0.228033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PE_R478_396,0.099132,0.012226,2.090906,0.937016,0.432914,0.422205,-0.034455,0.301893,-0.417816,0.567447,...,-0.318979,0.567542,-0.176940,-1.468123,0.858104,0.097731,-0.573343,-0.164230,0.004873,-0.195060
PE_R478_397,0.034352,-0.037069,0.652913,-0.084482,0.471556,0.067670,0.048786,1.311366,0.047220,-0.000537,...,0.953380,2.234465,0.233921,-0.020321,3.746860,0.025703,0.553025,0.145132,0.019710,2.857327
PE_R478_398,0.066884,0.005657,0.025657,-0.369096,-0.940943,-0.833491,-0.035938,-0.282643,0.902980,-0.354449,...,0.373973,-0.330692,0.003094,0.760417,-0.094866,-0.042590,0.295296,0.252283,-0.597332,0.102647
PE_R478_399,0.020281,-0.033391,0.115515,0.252649,0.799482,-0.555303,-0.095176,0.147232,-0.232622,0.275772,...,-0.294149,2.978748,-0.111313,-0.910355,0.684876,-0.089939,-0.454858,-0.286652,-0.528971,-0.131158
PE_R478_400,0.025702,0.052278,0.069588,0.085579,-0.847707,-0.578246,-0.034066,-0.313569,-0.271985,0.445230,...,0.034440,-0.259372,-0.228458,-0.224602,-0.230825,-0.132997,-0.373230,-0.033207,-0.627025,0.148722

In [4]:
pro_data.to_csv("./Data/pro_data_clean_mapped.csv", index=True)